services:
  - type: web
    name: mini-expense-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: cd ../client && npm install && npm run build && cd ../server && npm install
    startCommand: node server.js
